export default [
  {
    backdrop_path: "/xi1VSt3DtkevUmzCx2mNlCoDe74.jpg",
    id: 917496,
    title: "Beetlejuice Beetlejuice",
    original_title: "Beetlejuice Beetlejuice",
    overview:
      "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Betelgeuse, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
    poster_path: "/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [35, 14, 27],
    popularity: 3756.736,
    release_date: "2024-09-04",
    video: false,
    vote_average: 7.2,
    vote_count: 1163,
  },
  {
    backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    id: 533535,
    title: "Deadpool & Wolverine",
    original_title: "Deadpool & Wolverine",
    overview:
      "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [28, 35, 878],
    popularity: 3911.201,
    release_date: "2024-07-24",
    video: false,
    vote_average: 7.72,
    vote_count: 4357,
  },
  {
    backdrop_path: "/reNf6GBzOe48l9WEnFOxXgW56Vg.jpg",
    id: 889737,
    title: "Joker: Folie à Deux",
    original_title: "Joker: Folie à Deux",
    overview:
      "While struggling with his dual identity, Arthur Fleck not only stumbles upon true love, but also finds the music that's always been inside him.",
    poster_path: "/if8QiqCI7WAGImKcJCfzp6VTyKA.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [18, 80, 53],
    popularity: 957.346,
    release_date: "2024-10-01",
    video: false,
    vote_average: 5.8,
    vote_count: 703,
  },
  {
    backdrop_path: "/jlWk4J1sV1EHgkjhvsN7EdzGvOx.jpg",
    id: 933260,
    title: "The Substance",
    original_title: "The Substance",
    overview:
      "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
    poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [27, 18, 878],
    popularity: 2133.635,
    release_date: "2024-09-07",
    video: false,
    vote_average: 7.372,
    vote_count: 334,
  },
  {
    backdrop_path: "/3m0j3hCS8kMAaP9El6Vy5Lqnyft.jpg",
    id: 1125510,
    title: "The Platform 2",
    original_title: "El hoyo 2",
    overview:
      "After a mysterious leader imposes his law in a brutal system of vertical cells, a new arrival battles against a dubious food distribution method.",
    poster_path: "/izuzUb0sDokqp9o8utVfsrSJuy5.jpg",
    media_type: "movie",
    adult: false,
    original_language: "es",
    genre_ids: [878, 53, 18, 27],
    popularity: 2928.178,
    release_date: "2024-09-27",
    video: false,
    vote_average: 5.69,
    vote_count: 473,
  },
  {
    backdrop_path: "/9R9Za5kybgl5AhuCNoK3gngaBdG.jpg",
    id: 1114513,
    title: "Speak No Evil",
    original_title: "Speak No Evil",
    overview:
      "When an American family is invited to spend the weekend at the idyllic country estate of a charming British family they befriended on vacation, what begins as a dream holiday soon warps into a snarled psychological nightmare.",
    poster_path: "/fDtkrO2OAF8LKQTdzYmu1Y7lCLB.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [27, 53],
    popularity: 982.196,
    release_date: "2024-09-11",
    video: false,
    vote_average: 7.3,
    vote_count: 619,
  },
  {
    backdrop_path: "/4zlOPT9CrtIX05bBIkYxNZsm5zN.jpg",
    id: 1184918,
    title: "The Wild Robot",
    original_title: "The Wild Robot",
    overview:
      "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
    poster_path: "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [16, 878, 10751],
    popularity: 1822.697,
    release_date: "2024-09-12",
    video: false,
    vote_average: 8.109,
    vote_count: 201,
  },
  {
    backdrop_path: "/uXDwP5qPhuRyPpQ7WkLbE6t2z5W.jpg",
    id: 877817,
    title: "Wolfs",
    original_title: "Wolfs",
    overview:
      "Hired to cover up a high-profile crime, a fixer soon finds his night spiralling out of control when he's forced to work with an unexpected counterpart.",
    poster_path: "/vOX1Zng472PC2KnS0B9nRfM8aaZ.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [35, 53, 28],
    popularity: 851.503,
    release_date: "2024-09-20",
    video: false,
    vote_average: 6.6,
    vote_count: 457,
  },
  {
    backdrop_path: "/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg",
    id: 1022789,
    title: "Inside Out 2",
    original_title: "Inside Out 2",
    overview:
      "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
    poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [16, 10751, 12, 35, 18],
    popularity: 1492.726,
    release_date: "2024-06-11",
    video: false,
    vote_average: 7.632,
    vote_count: 4281,
  },
  {
    backdrop_path: "/g1z1ZvYKcmk9EnVOTYXR6vkNjkZ.jpg",
    id: 1087822,
    title: "Hellboy: The Crooked Man",
    original_title: "Hellboy: The Crooked Man",
    overview:
      "Hellboy and a rookie BPRD agent get stranded in 1950s rural Appalachia. There, they discover a small community haunted by witches, led by a local devil with a troubling connection to Hellboy's past: the Crooked Man.",
    poster_path: "/iz2GabtToVB05gLTVSH7ZvFtsMM.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [14, 27, 28],
    popularity: 682.38,
    release_date: "2024-08-29",
    video: false,
    vote_average: 4.8,
    vote_count: 94,
  },
  {
    backdrop_path: "/jf1V00dZdNkVfEq7VPk8frrlELk.jpg",
    id: 748230,
    title: "Salem's Lot",
    original_title: "Salem's Lot",
    overview:
      "Author Ben Mears returns to his childhood home of Jerusalem's Lot only to discover his hometown is being preyed upon by a bloodthirsty vampire.",
    poster_path: "/j7ncdqBVufydVzVtxmXu8Ago4ox.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [27, 9648],
    popularity: 617.554,
    release_date: "2024-10-03",
    video: false,
    vote_average: 6.343,
    vote_count: 223,
  },
  {
    backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
    id: 519182,
    title: "Despicable Me 4",
    original_title: "Despicable Me 4",
    overview:
      "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
    poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [16, 10751, 35, 28],
    popularity: 2091.83,
    release_date: "2024-06-20",
    video: false,
    vote_average: 7.1,
    vote_count: 1955,
  },
  {
    backdrop_path: "/sIzZQdXY21sEks9lGkGuXzqdGSA.jpg",
    id: 4011,
    title: "Beetlejuice",
    original_title: "Beetlejuice",
    overview:
      "A newly dead New England couple seeks help from a deranged demon exorcist to scare an affluent New York family out of their home.",
    poster_path: "/nnl6OWkyPpuMm595hmAxNW3rZFn.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [14, 35],
    popularity: 460.465,
    release_date: "1988-03-30",
    video: false,
    vote_average: 7.38,
    vote_count: 7280,
  },
  {
    backdrop_path: "/3LVVSvAkQGbL5fvG4VM3GfMaZBe.jpg",
    id: 1052280,
    title: "It's What's Inside",
    original_title: "It's What's Inside",
    overview:
      "A pre-wedding reunion descends into a psychological nightmare for a group of college friends when a surprise guest arrives with a mysterious suitcase.",
    poster_path: "/32Lfs4nbLehgbXI8VTeYg5jgIQt.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [35, 9648, 27, 878],
    popularity: 454.132,
    release_date: "2024-01-19",
    video: false,
    vote_average: 6.353,
    vote_count: 160,
  },
  {
    backdrop_path: "/xlkclSE4aq7r3JsFIJRgs21zUew.jpg",
    id: 1034541,
    title: "Terrifier 3",
    original_title: "Terrifier 3",
    overview:
      "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
    poster_path: "/7NDHoebflLwL1CcgLJ9wZbbDrmV.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [27, 53],
    popularity: 1942.148,
    release_date: "2024-10-09",
    video: false,
    vote_average: 7.2,
    vote_count: 33,
  },
  {
    backdrop_path: "/8cZ6OlVZv9FRZRfmDrkmu6Dheye.jpg",
    id: 814889,
    title: "Never Let Go",
    original_title: "Never Let Go",
    overview:
      "As an evil takes over the world beyond their front doorstep, the only protection for a mother and her twin sons is their house and their family’s protective bond.",
    poster_path: "/3EpZ2ksjijmdr8BhISP03PYzNFW.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [27, 18],
    popularity: 135.278,
    release_date: "2024-09-18",
    video: false,
    vote_average: 5.628,
    vote_count: 74,
  },
  {
    backdrop_path: "/zNZI9ckVF7uATRBQ7KNITHD036B.jpg",
    id: 863873,
    title: "Caddo Lake",
    original_title: "Caddo Lake",
    overview:
      "When an 8-year-old girl mysteriously vanishes, a series of past deaths and disappearances begins to link together.",
    poster_path: "/sv1IoM6xlCdAoOzUmgB9XTnADC.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [18, 9648, 878, 53],
    popularity: 172.246,
    release_date: "2024-10-09",
    video: false,
    vote_average: 7.6,
    vote_count: 68,
  },
  {
    backdrop_path: "/m1DkRQbNXjs2RYC0FP4r6mdaLCi.jpg",
    id: 698687,
    title: "Transformers One",
    original_title: "Transformers One",
    overview:
      "The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but once were friends bonded like brothers who changed the fate of Cybertron forever.",
    poster_path: "/qbkAqmmEIZfrCO8ZQAuIuVMlWoV.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [16, 878, 12, 10751, 28],
    popularity: 668.25,
    release_date: "2024-09-11",
    video: false,
    vote_average: 7.4,
    vote_count: 139,
  },
  {
    backdrop_path: "/NqqLef2ITlK8olXT4iFuUXFwSh.jpg",
    id: 840705,
    title: "Blink Twice",
    original_title: "Blink Twice",
    overview:
      "When tech billionaire Slater King meets cocktail waitress Frida at his fundraising gala, he invites her to join him and his friends on a dream vacation on his private island. But despite the epic setting, beautiful people, ever-flowing champagne, and late-night dance parties, Frida can sense that there’s something sinister hiding beneath the island’s lush façade.",
    poster_path: "/lZGOK0I2DJSRlEPNOAFTSNxSjDD.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [9648, 53, 27],
    popularity: 511.364,
    release_date: "2024-08-21",
    video: false,
    vote_average: 6.812,
    vote_count: 630,
  },
  {
    backdrop_path: "/1bWwaeVSFeytOBYNNEjZwH3VpFj.jpg",
    id: 1186532,
    title: "The Forge",
    original_title: "The Forge",
    overview:
      "19 year old Isaiah Wright lives for basketball and video games. A year out of high school, he has no job, no plans, and no idea how to be a man. At odds with his single mother Cynthia, Isaiah is given an ultimatum – to step up or move out. Feeling the pull from his friends and the push from his mom, Isaiah is hired by Moore Fitness, unaware of how the owner will personally impact his life. With the prayers of his mother and unexpected guidance from his new mentor, Isaiah is forced to deal with his past, sacrifice his selfishness and discover how God might have a greater purpose for his life.",
    poster_path: "/vXW1I7HGZkeGUqw8QpGFiDA31Ih.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [18, 10751],
    popularity: 407.35,
    release_date: "2024-08-22",
    video: false,
    vote_average: 7.4,
    vote_count: 28,
  },
];
